include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    always_use_package_imports: true
    avoid_redundant_argument_values: true
    use_build_context_synchronously: false
    
